title: 가끔씩 영어로 부끄러워하는 콘솔창의 에러양
description: 'A Jekyll Blog Theme For Hackers'
author:
  name: 'necteo'
  email: 'jaehwa06@naver.com'
  url: 'necteo.github.io'

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments:
        append: |
          <script src="https://giscus.app/client.js"
                  data-repo="[ENTER REPO HERE]"
                  data-repo-id="[ENTER REPO ID HERE]"
                  data-category="[ENTER CATEGORY NAME HERE]"
                  data-category-id="[ENTER CATEGORY ID HERE]"
                  data-mapping="pathname"
                  data-strict="0"
                  data-reactions-enabled="1"
                  data-emit-metadata="0"
                  data-input-position="bottom"
                  data-theme="preferred_color_scheme"
                  data-lang="ko"
                  crossorigin="anonymous"
                  async>
          </script>

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: 'necteo'
year: '2025'
